### ISSUE TITLE
FlagBrowser object does not understand #newNotebook

### ISSUE THREAD

**Issue by jvalteren** [jecisc/FlagBrowser#1]
Hi Cyril,
I would like to use your FlagBrowser. However, when clicking on the toolbar button 'Flags Browser' I get an error telling me it doesn't understand #newNotebook.

In the #initializeWidgets method (below), #newNotebook and NotebookPage are unimplemented/unreferenced.

```smalltalk
initializeWidgets
	tabs := self newNotebook.

	FBPagePresenter allPages do: [ :aPage | tabs addPage: (NotebookPage title: aPage title icon: (self iconNamed: aPage icon) provider: [ self instantiate: aPage ]) ]
```

**Comment by jecisc** [comment]
This is fixed in the latest version
